---
# See https://docs.ansible.com/projects/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: microsoft
name: scvmm
version: 1.0.0
readme: README.md
authors:
  - Steve Fulmer (github.com/stevefulme1)
  - Hen Yaish (github.com/Yaish25491)
description: Ansible Collection for managing Microsoft System Center Virtual Machine Manager (SCVMM) infrastructure.
license_file: LICENSE
tags:
  - scvmm
  - windows
  - hyperv
  - virtualization
  - infrastructure
repository: https://github.com/ansible-collections/microsoft.scvmm
homepage: https://github.com/ansible-collections/microsoft.scvmm
issues: https://github.com/ansible-collections/microsoft.scvmm/issues
dependencies:
  "ansible.windows": ">=2.0.0"
build_ignore:
  - .gitignore
  - .github
  - .vscode
  - tests/output
  - changelogs/.plugin-cache.yaml
